version: "3.9"
services:
  app:
    build:
      context: DjangoProject/
    ports:
      - "8000:8000"
    env_file:
      - _envs/local/api.env
    volumes:
      - ./teach_me_skills:/app

  postgres:
    image: postgres
    environment:
      POSTGRES_BD: "TMS"
      POSTGRES_USER: "TMS_USER"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"